Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1600"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y apache2 \
                        ghostscript \
                        libapache2-mod-php \
                        mysql-server \
                        php \
                        php-bcmath \
                        php-curl \
                        php-imagick \
                        php-intl \
                        php-json \
                        php-mbstring \
                        php-mysql \
                        php-xml \
                        php-zip

    sudo mkdir -p /srv/www
    sudo chown www-data: /srv/www
    curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www

    cat > /etc/apache2/sites-available/wordpress.conf <<EOF
<VirtualHost *:80>
       DocumentRoot /srv/www/wordpress
       <Directory /srv/www/wordpress>
           Options FollowSymLinks
           AllowOverride Limit Options FileInfo
           DirectoryIndex index.php
           Require all granted
       </Directory>
       <Directory /srv/www/wordpress/wp-content>
           Options FollowSymLinks
           Require all granted
       </Directory>
</VirtualHost>
EOF

    sudo a2ensite wordpress
    sudo a2enmod rewrite
    sudo a2dissite 000-default

    sudo systemctl restart apache2

    mysql -u root -e "CREATE DATABASE wordpress;"
    mysql -u root -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY '12345';"
    mysql -u root -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO 'wordpress'@'localhost';"
    mysql -u root -e "FLUSH PRIVILEGES;"

    sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
    sudo sed -i "s/database_name_here/wordpress/" /srv/www/wordpress/wp-config.php
    sudo sed -i "s/username_here/wordpress/" /srv/www/wordpress/wp-config.php
    sudo sed -i "s/password_here/12345/" /srv/www/wordpress/wp-config.php

    sudo systemctl restart mysql
    sudo systemctl restart apache2

  SHELL
end
